### CIS3120 Homework 1
- Due by March 8th 
- Submit through the blackboard link
- Submit with the notebook file (.ipynb)

1. Write a Python program to filter integers (1-50) into two lists (even numbers and odd numbers)<br>
 **(using Lambda argument)**

In [1]:
#Your answer
nums = list(range(1, 51))
print("\nEven numbers:")
even_nums = list(filter(lambda x: x%2 == 0, nums))
print(even_nums)
print("\nOdd numbers:")
odd_nums = list(filter(lambda x: x%2 != 0, nums))
print(odd_nums)

Even numbers:
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]

Odd numbers:
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]

2. Create a list and find numbers from 1 to 200, which are divisible by 2-9 (use for loop)

In [2]:
#Your answer
newList = [] #create list
for i in range(1,201): # numbers 1 through 200
    for j in range(2,10): #checking for dividibility from numbers 2 through 9
        if (i%j==0): #if iteration is divisible by 2-9
            newList.append(str(i)) #add divisible numbers to the list
list2 = []#create new list to remove duplicates
for a in newList:#for every number in old list
    if a not in list2:#if number is not in list2
        list2.append(a)#add number to new list
print(list2)
#print (', '.join(newList)) #joining numbers into the list

['2', '3', '4', '5', '6', '7', '8', '9', '10', '12', '14', '15', '16', '18', '20', '21', '22', '24', '25', '26', '27', '28', '30', '32', '33', '34', '35', '36', '38', '39', '40', '42', '44', '45', '46', '48', '49', '50', '51', '52', '54', '55', '56', '57', '58', '60', '62', '63', '64', '65', '66', '68', '69', '70', '72', '74', '75', '76', '77', '78', '80', '81', '82', '84', '85', '86', '87', '88', '90', '91', '92', '93', '94', '95', '96', '98', '99', '100', '102', '104', '105', '106', '108', '110', '111', '112', '114', '115', '116', '117', '118', '119', '120', '122', '123', '124', '125', '126', '128', '129', '130', '132', '133', '134', '135', '136', '138', '140', '141', '142', '144', '145', '146', '147', '148', '150', '152', '153', '154', '155', '156', '158', '159', '160', '161', '162', '164', '165', '166', '168', '170', '171', '172', '174', '175', '176', '177', '178', '180', '182', '183', '184', '185', '186', '188', '189', '190', '192', '194', '195', '196', '198', '200']

3. Create a list and find numbers from 1 to 200, which are divisible by 2-9 (use list comprehension)

In [43]:
#nested list comprehension
[x for x in range(1,201) for j in range(2,10) if x%j==0]

[2,
 3,
 4,
 4,
 5,
 6,
 6,
 6,
 7,
 8,
 8,
 8,
 9,
 9,
 10,
 10,
 12,
 12,
 12,
 12,
 14,
 14,
 15,
 15,
 16,
 16,
 16,
 18,
 18,
 18,
 18,
 20,
 20,
 20,
 21,
 21,
 22,
 24,
 24,
 24,
 24,
 24,
 25,
 26,
 27,
 27,
 28,
 28,
 28,
 30,
 30,
 30,
 30,
 32,
 32,
 32,
 33,
 34,
 35,
 35,
 36,
 36,
 36,
 36,
 36,
 38,
 39,
 40,
 40,
 40,
 40,
 42,
 42,
 42,
 42,
 44,
 44,
 45,
 45,
 45,
 46,
 48,
 48,
 48,
 48,
 48,
 49,
 50,
 50,
 51,
 52,
 52,
 54,
 54,
 54,
 54,
 55,
 56,
 56,
 56,
 56,
 57,
 58,
 60,
 60,
 60,
 60,
 60,
 62,
 63,
 63,
 63,
 64,
 64,
 64,
 65,
 66,
 66,
 66,
 68,
 68,
 69,
 70,
 70,
 70,
 72,
 72,
 72,
 72,
 72,
 72,
 74,
 75,
 75,
 76,
 76,
 77,
 78,
 78,
 78,
 80,
 80,
 80,
 80,
 81,
 81,
 82,
 84,
 84,
 84,
 84,
 84,
 85,
 86,
 87,
 88,
 88,
 88,
 90,
 90,
 90,
 90,
 90,
 91,
 92,
 92,
 93,
 94,
 95,
 96,
 96,
 96,
 96,
 96,
 98,
 98,
 99,
 99,
 100,
 100,
 100,
 102,
 102,
 102,
 104,
 104,
 104,
 105,
 105,
 105,
 106,
 108,
 108,
 108,
 108,
 108,
 110,
 110,
 111,
 112,
 112,
 112,
 112,
 114,
 114,
 114,
 115,
 116,
 116,
 117,
 117,
 118,
 119,
 120,
 120,
 120,
 120,
 120,
 120,
 122,
 123,
 124,
 124,
 125,
 126,
 126,
 126,
 126,
 126,
 128,
 128,
 128,
 129,
 130,
 130,
 132,
 132,
 132,
 132,
 133,
 134,
 135,
 135,
 135,
 136,
 136,
 136,
 138,
 138,
 138,
 140,
 140,
 140,
 140,
 141,
 142,
 144,
 144,
 144,
 144,
 144,
 144,
 145,
 146,
 147,
 147,
 148,
 148,
 150,
 150,
 150,
 150,
 152,
 152,
 152,
 153,
 153,
 154,
 154,
 155,
 156,
 156,
 156,
 156,
 158,
 159,
 160,
 160,
 160,
 160,
 161,
 162,
 162,
 162,
 162,
 164,
 164,
 165,
 165,
 166,
 168,
 168,
 168,
 168,
 168,
 168,
 170,
 170,
 171,
 171,
 172,
 172,
 174,
 174,
 174,
 175,
 175,
 176,
 176,
 176,
 177,
 178,
 180,
 180,
 180,
 180,
 180,
 180,
 182,
 182,
 183,
 184,
 184,
 184,
 185,
 186,
 186,
 186,
 188,
 188,
 189,
 189,
 189,
 190,
 190,
 192,
 192,
 192,
 192,
 192,
 194,
 195,
 195,
 196,
 196,
 196,
 198,
 198,
 198,
 198,
 200,
 200,
 200,
 200]

4. Create a list to get the first 11 Fibonacci series.  <br>
Note : The Fibonacci Sequence is the series of numbers :
0, 1, 1, 2, 3, 5, 8, 13, 21, .... 
<br>
Every next number is found by adding up the two numbers before it. <br>
Expected Output : 1 1 2 3 5 8 13 21 34 55 89

In [4]:
#Your answer
fib1, fib2 = 1, 1
count = 0
while count < 11:
    print(fib1)
    seq = fib1 + fib2
    # update values
    fib1 = fib2
    fib2 = seq
    count += 1

1
1
2
3
5
8
13
21
34
55
89

5. Count the number of paragraphs, tables, and external links from the webpage: https://en.wikipedia.org/wiki/Baruch_College

In [5]:
pip install -U beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /Users/amarisefthimiou/opt/anaconda3/lib/python3.9/site-packages (4.10.0)
Requirement already satisfied: soupsieve>1.2 in /Users/amarisefthimiou/opt/anaconda3/lib/python3.9/site-packages (from beautifulsoup4) (2.2.1)
Note: you may need to restart the kernel to use updated packages.

In [6]:
# Your answer
from bs4 import BeautifulSoup as bs
import requests
url = 'https://en.wikipedia.org/wiki/Baruch_College'
r = requests.get(url)
html_contents = r.text
html_soup = bs(html_contents)
print(len(html_soup.findAll('p'))) #paragraphs
print(len(html_soup.findAll('table'))) #tables
print(len(html_soup.findAll('a')[1].get('href'))) #external links

34
8
8

6. Print the text in the first paragraph from the following html document:

In [7]:
html_doc = """
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;
charset=iso-8859-1">
<title>An example of HTML page</title>
</head>
<body>
<h2>This is an example HTML page</h2>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit,
aliquet iaculis est. Curabitur porttitor nisi vel lacus euismod egestas. In hac
habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus
sagittis pulvinar facilisis. Donec vel odio volutpat tortor volutpat commodo.
Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed pellentesque
adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim
elementum nunc, non elementum felis condimentum eu. In in turpis quis erat
imperdiet vulputate. Pellentesque mauris turpis, dignissim sed iaculis eu,
euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl
euismod porta.</p>
<p><a href="https://www.w3resource.com/html/HTML-tutorials.php">Learn HTML from
w3resource.com</a></p>
<p><a href="https://www.w3resource.com/css/CSS-tutorials.php">Learn CSS from 
w3resource.com</a></p>
</body>
</html>
"""

In [8]:
#Your answer

from bs4 import BeautifulSoup as bs
import requests
url = 'https://www.w3resource.com/html/HTML-tutorials.php'
bsoup = bs(html_doc, 'html.parser')
print(bsoup.find_all('p')[0].text)

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit,
aliquet iaculis est. Curabitur porttitor nisi vel lacus euismod egestas. In hac
habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus
sagittis pulvinar facilisis. Donec vel odio volutpat tortor volutpat commodo.
Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed pellentesque
adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim
elementum nunc, non elementum felis condimentum eu. In in turpis quis erat
imperdiet vulputate. Pellentesque mauris turpis, dignissim sed iaculis eu,
euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl
euismod porta.

7. Write a Python program to find all the link tags and list the first ten from the webpage https://www.baruch.cuny.edu

In [9]:
# Your answer
from bs4 import BeautifulSoup as bs
import requests
url = 'https://www.baruch.cuny.edu/'
reqs = requests.get(url)
besoup = bs(reqs.text, 'lxml')
print(besoup.find_all('a')[0:10])

[<a href="https://forward.baruch.cuny.edu/">Baruch Forward</a>, <a class="skip-to-content" href="#content" title="Skip to content">Skip to content</a>, <a href="https://forward.baruch.cuny.edu/">Baruch Forward</a>, <a href="https://www.baruch.cuny.edu/bctc/blackboard/">Blackboard</a>, <a href="https://blogs.baruch.cuny.edu/">Blogs@Baruch</a>, <a href="https://home.cunyfirst.cuny.edu/">CUNYfirst</a>, <a href="https://www.baruch.cuny.edu/bctc/degreeworks/">Degree Works</a>, <a href="https://www.digitalmeasures.com/login/baruch-cuny/faculty/authentication/showLogin.do?shce_test=1583939526202">Digital Measures</a>, <a href="https://baruch.cuny.edu/epaf/">ePAF</a>, <a href="#">Faculty  &amp; Staff </a>]

8. Create a Python dictionary to get the title, rating and the url of the top 50 movie from IMDb movie database: https://www.imdb.com/chart/top/?ref_=nv_mv_250

In [27]:
from bs4 import BeautifulSoup
import requests
import re
url = 'http://www.imdb.com/chart/top'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'lxml')

movies = soup.select('td.titleColumn')#get the movies
links = [a.attrs.get('href') for a in soup.select('td.titleColumn a')]#get the links

imdb = []
for index in range(0,50):#only want to get the 50th value
    movie_string= movies[index].get_text() 
    movie = (' '.join(movie_string.split()).replace('.', '')) #clean up the position of the rank number in the output
    movie_title = movie[len(str(index))+1:-7]#titles of the movies
    rank = movie[:len(str(index))-(len(movie))] #position/rank number of the movie
    data = {"movie_title": movie_title,
            "rank": rank,
            "link": links[index]}
    imdb.append(data)

for item in imdb:#print out the 50th value of the dictionary
    print("rank:", item['rank'],'-',"title:", item['movie_title'],"-","link:", "http://www.imdb.com"+item['link'])

rank: 1 - title: The Shawshank Redemption - link: http://www.imdb.com/title/tt0111161/
rank: 2 - title: The Godfather - link: http://www.imdb.com/title/tt0068646/
rank: 3 - title: The Dark Knight - link: http://www.imdb.com/title/tt0468569/
rank: 4 - title: The Godfather: Part II - link: http://www.imdb.com/title/tt0071562/
rank: 5 - title: 12 Angry Men - link: http://www.imdb.com/title/tt0050083/
rank: 6 - title: Schindler's List - link: http://www.imdb.com/title/tt0108052/
rank: 7 - title: The Lord of the Rings: The Return of the King - link: http://www.imdb.com/title/tt0167260/
rank: 8 - title: Pulp Fiction - link: http://www.imdb.com/title/tt0110912/
rank: 9 - title: The Lord of the Rings: The Fellowship of the Ring - link: http://www.imdb.com/title/tt0120737/
rank: 1 - title:  The Good, the Bad and the Ugly - link: http://www.imdb.com/title/tt0060196/
rank: 11 - title: Forrest Gump - link: http://www.imdb.com/title/tt0109830/
rank: 12 - title: Fight Club - link: http://www.imdb.com/title/tt0137523/
rank: 13 - title: Inception - link: http://www.imdb.com/title/tt1375666/
rank: 14 - title: The Lord of the Rings: The Two Towers - link: http://www.imdb.com/title/tt0167261/
rank: 15 - title: Star Wars: Episode V - The Empire Strikes Back - link: http://www.imdb.com/title/tt0080684/
rank: 16 - title: The Matrix - link: http://www.imdb.com/title/tt0133093/
rank: 17 - title: Goodfellas - link: http://www.imdb.com/title/tt0099685/
rank: 18 - title: One Flew Over the Cuckoo's Nest - link: http://www.imdb.com/title/tt0073486/
rank: 19 - title: Se7en - link: http://www.imdb.com/title/tt0114369/
rank: 20 - title: Seven Samurai - link: http://www.imdb.com/title/tt0047478/
rank: 21 - title: It's a Wonderful Life - link: http://www.imdb.com/title/tt0038650/
rank: 22 - title: The Silence of the Lambs - link: http://www.imdb.com/title/tt0102926/
rank: 23 - title: Saving Private Ryan - link: http://www.imdb.com/title/tt0120815/
rank: 24 - title: City of God - link: http://www.imdb.com/title/tt0317248/
rank: 25 - title: Life Is Beautiful - link: http://www.imdb.com/title/tt0118799/
rank: 26 - title: The Green Mile - link: http://www.imdb.com/title/tt0120689/
rank: 27 - title: Star Wars - link: http://www.imdb.com/title/tt0076759/
rank: 28 - title: Interstellar - link: http://www.imdb.com/title/tt0816692/
rank: 29 - title: Terminator 2: Judgment Day - link: http://www.imdb.com/title/tt0103064/
rank: 30 - title: Back to the Future - link: http://www.imdb.com/title/tt0088763/
rank: 31 - title: Spirited Away - link: http://www.imdb.com/title/tt0245429/
rank: 32 - title: Psycho - link: http://www.imdb.com/title/tt0054215/
rank: 33 - title: Léon: The Professional - link: http://www.imdb.com/title/tt0110413/
rank: 34 - title: The Pianist - link: http://www.imdb.com/title/tt0253474/
rank: 35 - title: Parasite - link: http://www.imdb.com/title/tt6751668/
rank: 36 - title: The Lion King - link: http://www.imdb.com/title/tt0110357/
rank: 37 - title: Gladiator - link: http://www.imdb.com/title/tt0172495/
rank: 38 - title: American History X - link: http://www.imdb.com/title/tt0120586/
rank: 39 - title: The Usual Suspects - link: http://www.imdb.com/title/tt0114814/
rank: 40 - title: The Departed - link: http://www.imdb.com/title/tt0407887/
rank: 41 - title: Spider-Man: No Way Home - link: http://www.imdb.com/title/tt10872600/
rank: 42 - title: The Prestige - link: http://www.imdb.com/title/tt0482571/
rank: 43 - title: Casablanca - link: http://www.imdb.com/title/tt0034583/
rank: 44 - title: Whiplash - link: http://www.imdb.com/title/tt2582802/
rank: 45 - title: The Intouchables - link: http://www.imdb.com/title/tt1675434/
rank: 46 - title: Modern Times - link: http://www.imdb.com/title/tt0027977/
rank: 47 - title: Once Upon a Time in the West - link: http://www.imdb.com/title/tt0064116/
rank: 48 - title: Hara-Kiri - link: http://www.imdb.com/title/tt0056058/
rank: 49 - title: Grave of the Fireflies - link: http://www.imdb.com/title/tt0095327/
rank: 50 - title: Alien - link: http://www.imdb.com/title/tt0078748/

In [1]:
print('amaris')

amaris